apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: oai-ran-operators
  name: oai-ran-operator

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: oai-ran-operator-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - workload.nephio.org
  resources:
  - randeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workload.nephio.org
  resources:
  - randeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ref.nephio.org
  resources:
  - configs
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oai-ran-operator-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oai-ran-operator-cluster-role
subjects:
  - kind: ServiceAccount
    name: oai-ran-operator
    namespace: oai-ran-operators

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: oai-ran-operators
  name: oai-ran-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oai-ran-operator
      app.kubernetes.io/component: controller
  template:
    metadata:
      name: oai-ran-operator
      labels:
        app.kubernetes.io/name: oai-ran-operator
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: oai-ran-operator
      containers:
      - name: operator
        image: oai-ran-operator:v1.0.0
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
