apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: oai-ue/oai-nr-ue
  name: oai-nr-ue
  namespace: oai-ue
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|oai-ue|oai-nr-ue'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oai-nr-ue
      app.kubernetes.io/instance: nrue
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oai-nr-ue
        app.kubernetes.io/instance: nrue
        app: oai-nr-ue
    spec:
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      imagePullSecrets:
      - name: regcred
      containers:
      - name: nr-ue
        image: "oaisoftwarealliance/oai-nr-ue:v2.1.0"
        securityContext:
          privileged: true
        env:
        - name: USE_ADDITIONAL_OPTIONS
        # oai-gnb-du.oai-ran-du
          value: "--sa -E --rfsimulator.serveraddr 192.168.1.21 --rfsim --log_config.global_log_options level,nocolor,time -r 106 --numerology 1 -C 3619200000 --uicc0.imsi 001010000000100 "  
        volumeMounts:
        - mountPath: /opt/oai-nr-ue/etc/nr-ue.conf
          name: configuration
          subPath: nr-ue.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: oai-nr-ue-sa
      terminationGracePeriodSeconds: 5
      volumes:
      - configMap:
          defaultMode: 420
          name: oai-nr-ue-configmap
        name: configuration
